include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    [
      build/**,
      "**/*.freezed.dart",
      "**/*.g.dart",
      "**/*.gr.dart",
      "**/*.gen.dart",
    ]